"""add role enum to users

Revision ID: 63d5f3bb6a13
Revises: 9d7a0faf29e9
Create Date: 2026-02-16 13:00:06.341235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63d5f3bb6a13'
down_revision: Union[str, Sequence[str], None] = '9d7a0faf29e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = postgresql.ENUM('user', 'admin', name='user_role_enum')
    user_role_enum.create(op.get_bind())

    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='user_role_enum'), nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    user_role_enum = postgresql.ENUM('user', 'admin', name='user_role_enum')
    user_role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
